name: 📚 Propose new documentation
description: Identify a part of this repository that should be documented but isn’t
labels: [documentation]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in multiring.zig!

        Before suggesting improvements to our documentation, check the [issue tracker](https://github.com/ok-ryoko/multiring.zig/issues) to make sure someone hasn’t already made the same suggestion.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of conduct
      description: The community around this project has a [code of conduct](https://github.com/ok-ryoko/multiring.zig/blob/main/CODE_OF_CONDUCT.md) that all participants are expected to understand and follow.
      options:
        - label: I have read and agree to the community’s code of conduct.
          required: true

  - type: textarea
    attributes:
      label: Scope
      description: What needs to be documented?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Value proposition
      description: Why should it be documented?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Supporting information
      description: Provide additional context, examples, etc., to reinforce your proposal, if applicable.
    validations:
      required: false
