name: ci-shell
on:
  push:
    branches:
      - main
    paths:
      - '.githooks/**'

  pull_request:
    branches:
      - main
    paths:
      - '.githooks/**'

jobs:
  lint:
    runs-on:
      - ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print ShellCheck version
        run: shellcheck --version

      - name: Lint shell scripts
        run: shellcheck --format=gcc --shell=sh .githooks/**
