name: ci-shell
on:
  push:
    branches:
      - main
    paths:
      - '.githooks/**'

  pull_request:
    branches:
      - main
    paths:
      - '.githooks/**'

permissions:
  contents: read

jobs:
  check:
    runs-on:
      - ubuntu-22.04

    steps:
      - name: Checkout last commit on branch main
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Print ShellCheck version
        run: shellcheck --version

      - name: Lint shell scripts
        run: shellcheck --format=gcc --shell=sh .githooks/**
