name: ci-yaml
on:
  push:
    branches:
      - main
    paths:
      - '.github/**.yml'
      - '.yamllint'

  pull_request:
    branches:
      - main
    paths:
      - '.github/**.yml'
      - '.yamllint'

permissions:
  contents: read

jobs:
  check:
    runs-on:
      - ubuntu-22.04

    steps:
      - name: Checkout last commit on branch main
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Print yamllint version
        run: yamllint --version

      - name: Lint YAML files
        run: yamllint --no-warnings .github/ .yamllint
