name: ci-zig
on:
  push:
    branches:
      - main
    paths:
      - 'examples/**.zig'
      - 'src/**.zig'
      - 'build.zig'
      - 'build.zig.zon'

  pull_request:
    branches:
      - main
    paths:
      - 'examples/**.zig'
      - 'src/**.zig'
      - 'build.zig'
      - 'build.zig.zon'

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        version:
          - 0.13.0

    runs-on:
      - ubuntu-22.04

    steps:
      - name: Checkout last commit on branch main
        uses: actions/checkout@v3

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ matrix.version }}

      - name: Print Zig environment
        run: zig env

      - name: Check Zig source code formatting
        run: zig fmt --check examples/**.zig src/**.zig build.zig build.zig.zon

      - name: Build module
        run: zig build

      - name: Run module tests
        run: zig build test
